/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetAssetsForContractBodyInputAttributesInner.h"

namespace OpenAPI
{

/*
 * PlayerClientCommonStatsRequestInput
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientCommonStatsRequestInput : public Model
{
public:
    virtual ~PlayerClientCommonStatsRequestInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<PlayerClientGetAssetsForContractBodyInputAttributesInner>> Attributes;
	TOptional<int64> ChainId;
};

}
