/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientGetChainCurrenciesResponseDataInner
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetChainCurrenciesResponseDataInner : public Model
{
public:
    virtual ~PlayerClientGetChainCurrenciesResponseDataInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	double Decimals;
	enum class SymbolEnum
	{
		Beam,
		Wbeam,
		Usdc,
		Usdt,
		Imx,
		Wimx,
  	};

	static FString EnumToString(const SymbolEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SymbolEnum& EnumValue);
	SymbolEnum Symbol;
	FString Address;
};

}
