/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance : public Model
{
public:
    virtual ~PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Name;
	FString Symbol;
	double Decimals;
	TOptional<FString> LogoUri;
	int64 ChainId = 0;
	FString Balance;
};

}
