/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientGetOwnersResponsePagination
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetOwnersResponsePagination : public Model
{
public:
    virtual ~PlayerClientGetOwnersResponsePagination() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	double Count;
	TOptional<double> Limit;
	TOptional<double> Offset;
};

}
