/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

class PLAYERCLIENT_API PlayerClientMarketplaceApi
{
public:
	PlayerClientMarketplaceApi();
	~PlayerClientMarketplaceApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class AcceptAssetOfferRequest;
	class AcceptAssetOfferResponse;
	class BuyListedAssetRequest;
	class BuyListedAssetResponse;
	class CancelAssetOfferRequest;
	class CancelAssetOfferResponse;
	class CancelListingRequest;
	class CancelListingResponse;
	class CreateAssetOfferRequest;
	class CreateAssetOfferResponse;
	class GetAssetOffersRequest;
	class GetAssetOffersResponse;
	class GetChainCurrenciesRequest;
	class GetChainCurrenciesResponse;
	class GetListedAssetsRequest;
	class GetListedAssetsResponse;
	class GetListedAssetsForUserRequest;
	class GetListedAssetsForUserResponse;
	class GetUserAssetOffersRequest;
	class GetUserAssetOffersResponse;
	class GetUserOffersRequest;
	class GetUserOffersResponse;
	class ListAssetRequest;
	class ListAssetResponse;
	class RefreshContractRequest;
	class RefreshContractResponse;
	class RefreshTokenRequest;
	class RefreshTokenResponse;
	
    DECLARE_DELEGATE_OneParam(FAcceptAssetOfferDelegate, const AcceptAssetOfferResponse&);
    DECLARE_DELEGATE_OneParam(FBuyListedAssetDelegate, const BuyListedAssetResponse&);
    DECLARE_DELEGATE_OneParam(FCancelAssetOfferDelegate, const CancelAssetOfferResponse&);
    DECLARE_DELEGATE_OneParam(FCancelListingDelegate, const CancelListingResponse&);
    DECLARE_DELEGATE_OneParam(FCreateAssetOfferDelegate, const CreateAssetOfferResponse&);
    DECLARE_DELEGATE_OneParam(FGetAssetOffersDelegate, const GetAssetOffersResponse&);
    DECLARE_DELEGATE_OneParam(FGetChainCurrenciesDelegate, const GetChainCurrenciesResponse&);
    DECLARE_DELEGATE_OneParam(FGetListedAssetsDelegate, const GetListedAssetsResponse&);
    DECLARE_DELEGATE_OneParam(FGetListedAssetsForUserDelegate, const GetListedAssetsForUserResponse&);
    DECLARE_DELEGATE_OneParam(FGetUserAssetOffersDelegate, const GetUserAssetOffersResponse&);
    DECLARE_DELEGATE_OneParam(FGetUserOffersDelegate, const GetUserOffersResponse&);
    DECLARE_DELEGATE_OneParam(FListAssetDelegate, const ListAssetResponse&);
    DECLARE_DELEGATE_OneParam(FRefreshContractDelegate, const RefreshContractResponse&);
    DECLARE_DELEGATE_OneParam(FRefreshTokenDelegate, const RefreshTokenResponse&);
    
    FHttpRequestPtr AcceptAssetOffer(const AcceptAssetOfferRequest& Request, const FAcceptAssetOfferDelegate& Delegate = FAcceptAssetOfferDelegate()) const;
    FHttpRequestPtr BuyListedAsset(const BuyListedAssetRequest& Request, const FBuyListedAssetDelegate& Delegate = FBuyListedAssetDelegate()) const;
    FHttpRequestPtr CancelAssetOffer(const CancelAssetOfferRequest& Request, const FCancelAssetOfferDelegate& Delegate = FCancelAssetOfferDelegate()) const;
    FHttpRequestPtr CancelListing(const CancelListingRequest& Request, const FCancelListingDelegate& Delegate = FCancelListingDelegate()) const;
    FHttpRequestPtr CreateAssetOffer(const CreateAssetOfferRequest& Request, const FCreateAssetOfferDelegate& Delegate = FCreateAssetOfferDelegate()) const;
    FHttpRequestPtr GetAssetOffers(const GetAssetOffersRequest& Request, const FGetAssetOffersDelegate& Delegate = FGetAssetOffersDelegate()) const;
    FHttpRequestPtr GetChainCurrencies(const GetChainCurrenciesRequest& Request, const FGetChainCurrenciesDelegate& Delegate = FGetChainCurrenciesDelegate()) const;
    FHttpRequestPtr GetListedAssets(const GetListedAssetsRequest& Request, const FGetListedAssetsDelegate& Delegate = FGetListedAssetsDelegate()) const;
    FHttpRequestPtr GetListedAssetsForUser(const GetListedAssetsForUserRequest& Request, const FGetListedAssetsForUserDelegate& Delegate = FGetListedAssetsForUserDelegate()) const;
    FHttpRequestPtr GetUserAssetOffers(const GetUserAssetOffersRequest& Request, const FGetUserAssetOffersDelegate& Delegate = FGetUserAssetOffersDelegate()) const;
    FHttpRequestPtr GetUserOffers(const GetUserOffersRequest& Request, const FGetUserOffersDelegate& Delegate = FGetUserOffersDelegate()) const;
    FHttpRequestPtr ListAsset(const ListAssetRequest& Request, const FListAssetDelegate& Delegate = FListAssetDelegate()) const;
    FHttpRequestPtr RefreshContract(const RefreshContractRequest& Request, const FRefreshContractDelegate& Delegate = FRefreshContractDelegate()) const;
    FHttpRequestPtr RefreshToken(const RefreshTokenRequest& Request, const FRefreshTokenDelegate& Delegate = FRefreshTokenDelegate()) const;
    
private:
    void OnAcceptAssetOfferResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAcceptAssetOfferDelegate Delegate) const;
    void OnBuyListedAssetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FBuyListedAssetDelegate Delegate) const;
    void OnCancelAssetOfferResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCancelAssetOfferDelegate Delegate) const;
    void OnCancelListingResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCancelListingDelegate Delegate) const;
    void OnCreateAssetOfferResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateAssetOfferDelegate Delegate) const;
    void OnGetAssetOffersResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetAssetOffersDelegate Delegate) const;
    void OnGetChainCurrenciesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetChainCurrenciesDelegate Delegate) const;
    void OnGetListedAssetsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetListedAssetsDelegate Delegate) const;
    void OnGetListedAssetsForUserResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetListedAssetsForUserDelegate Delegate) const;
    void OnGetUserAssetOffersResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetUserAssetOffersDelegate Delegate) const;
    void OnGetUserOffersResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetUserOffersDelegate Delegate) const;
    void OnListAssetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListAssetDelegate Delegate) const;
    void OnRefreshContractResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FRefreshContractDelegate Delegate) const;
    void OnRefreshTokenResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FRefreshTokenDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
