/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetAssetListingsResponseDataInnerPriceAmount.h"
#include "PlayerClientGetAssetListingsResponseDataInnerPriceCurrency.h"

namespace OpenAPI
{

/*
 * PlayerClientGetAssetListingsResponseDataInnerPrice
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetAssetListingsResponseDataInnerPrice : public Model
{
public:
    virtual ~PlayerClientGetAssetListingsResponseDataInnerPrice() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<PlayerClientGetAssetListingsResponseDataInnerPriceCurrency> Currency;
	TOptional<PlayerClientGetAssetListingsResponseDataInnerPriceAmount> Amount;
	TOptional<PlayerClientGetAssetListingsResponseDataInnerPriceAmount> NetAmount;
};

}
