/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientCommonActivityRequestInput
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientCommonActivityRequestInput : public Model
{
public:
    virtual ~PlayerClientCommonActivityRequestInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<double> Limit;
	enum class TypesEnum
	{
		Ask,
		AskCancel,
		Bid,
		BidCancel,
		Sale,
		Mint,
		Transfer,
  	};

	static FString EnumToString(const TypesEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypesEnum& EnumValue);
	TOptional<TArray<TypesEnum>> Types;
	TOptional<double> ChainId;
};

}
