/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetTransactionsResponseDataInnerTransactionLogsInner.h"

namespace OpenAPI
{

/*
 * PlayerClientGetTransactionsResponseDataInnerTransaction
 *
 * The transaction object exists if you created the transaction deterministically and contains information about the on-chain transaction
 */
class PLAYERCLIENT_API PlayerClientGetTransactionsResponseDataInnerTransaction : public Model
{
public:
    virtual ~PlayerClientGetTransactionsResponseDataInnerTransaction() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FDateTime CreatedAt;
	TOptional<double> BlockNumber;
	TOptional<FString> Hash;
	TOptional<FString> GasUsed;
	TOptional<FString> GasFee;
	TOptional<double> Status;
	TOptional<TArray<PlayerClientGetTransactionsResponseDataInnerTransactionLogsInner>> Logs;
};

}
