/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetOnRampQuoteResponseQuoteInput.h"
#include "PlayerClientGetOnRampQuoteResponseQuoteOutput.h"

namespace OpenAPI
{

/*
 * PlayerClientGetOnRampQuoteResponseQuote
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetOnRampQuoteResponseQuote : public Model
{
public:
    virtual ~PlayerClientGetOnRampQuoteResponseQuote() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	PlayerClientGetOnRampQuoteResponseQuoteInput Input;
	PlayerClientGetOnRampQuoteResponseQuoteOutput Output;
};

}
