/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientPlayerOperationActionSignature
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientPlayerOperationActionSignature : public Model
{
public:
    virtual ~PlayerClientPlayerOperationActionSignature() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class TypeEnum
	{
		Message,
		TypedData,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
	FString Id;
	TOptional<TSharedPtr<FJsonValue>> Data;
	TOptional<FString> Signature;
	TOptional<FString> ActionId;
	TOptional<FString> Hash;
};

}
