/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetAttributesResponseDataInnerValuesInner.h"

namespace OpenAPI
{

/*
 * PlayerClientGetAttributesResponseDataInner
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetAttributesResponseDataInner : public Model
{
public:
    virtual ~PlayerClientGetAttributesResponseDataInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Key;
	enum class KindEnum
	{
		String,
		Number,
		Date,
		Range,
  	};

	static FString EnumToString(const KindEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, KindEnum& EnumValue);
	KindEnum Kind;
	TOptional<TArray<PlayerClientGetAttributesResponseDataInnerValuesInner>> Values;
};

}
