/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetActiveSessionResponseV2Session.h"

namespace OpenAPI
{

/*
 * PlayerClientGetActiveSessionResponseV2
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetActiveSessionResponseV2 : public Model
{
public:
    virtual ~PlayerClientGetActiveSessionResponseV2() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<PlayerClientGetActiveSessionResponseV2Session> Session;
};

}
