/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientGetTransactionsResponseDataInnerIntent.h"
#include "PlayerClientGetTransactionsResponseDataInnerTransaction.h"

namespace OpenAPI
{

/*
 * PlayerClientGetTransactionsResponseDataInner
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetTransactionsResponseDataInner : public Model
{
public:
    virtual ~PlayerClientGetTransactionsResponseDataInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString Id;
	FDateTime CreatedAt;
	FDateTime UpdatedAt;
	double ChainId;
	PlayerClientGetTransactionsResponseDataInnerIntent Intent;
	TOptional<PlayerClientGetTransactionsResponseDataInnerTransaction> Transaction;
};

}
