/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

class PLAYERCLIENT_API PlayerClientRampApi
{
public:
	PlayerClientRampApi();
	~PlayerClientRampApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class CreateOnrampRequestRequest;
	class CreateOnrampRequestResponse;
	class GetOnRampQuoteRequest;
	class GetOnRampQuoteResponse;
	
    DECLARE_DELEGATE_OneParam(FCreateOnrampRequestDelegate, const CreateOnrampRequestResponse&);
    DECLARE_DELEGATE_OneParam(FGetOnRampQuoteDelegate, const GetOnRampQuoteResponse&);
    
    FHttpRequestPtr CreateOnrampRequest(const CreateOnrampRequestRequest& Request, const FCreateOnrampRequestDelegate& Delegate = FCreateOnrampRequestDelegate()) const;
    FHttpRequestPtr GetOnRampQuote(const GetOnRampQuoteRequest& Request, const FGetOnRampQuoteDelegate& Delegate = FGetOnRampQuoteDelegate()) const;
    
private:
    void OnCreateOnrampRequestResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateOnrampRequestDelegate Delegate) const;
    void OnGetOnRampQuoteResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetOnRampQuoteDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
