/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientRampApi.h"
#include <string>
#include <stdexcept>
    
#include "PlayerClientBeamErrorResponse.h"
#include "PlayerClientCreateOnrampRequestInput.h"
#include "PlayerClientGetOnRampQuoteResponse.h"
#include "PlayerClientPlayerOperationResponse.h"

namespace OpenAPI
{

/* 

*/
class PLAYERCLIENT_API PlayerClientRampApi::CreateOnrampRequestRequest : public Request
{
public:
    virtual ~CreateOnrampRequestRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString EntityId;
	PlayerClientCreateOnrampRequestInput PlayerClientCreateOnrampRequestInput;
};

class PLAYERCLIENT_API PlayerClientRampApi::CreateOnrampRequestResponse : public Response
{
public:
    virtual ~CreateOnrampRequestResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    PlayerClientPlayerOperationResponse Content;
private:
    FString GetHttpStatusCategory(EHttpResponseCodes::Type InHttpResponseCode);
};

/* 

*/
class PLAYERCLIENT_API PlayerClientRampApi::GetOnRampQuoteRequest : public Request
{
public:
    virtual ~GetOnRampQuoteRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString EntityId;
	PlayerClientCreateOnrampRequestInput PlayerClientCreateOnrampRequestInput;
};

class PLAYERCLIENT_API PlayerClientRampApi::GetOnRampQuoteResponse : public Response
{
public:
    virtual ~GetOnRampQuoteResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    PlayerClientGetOnRampQuoteResponse Content;
private:
    FString GetHttpStatusCategory(EHttpResponseCodes::Type InHttpResponseCode);
};

}
