/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"
#include "PlayerClientCommonOperationResponseTransactionsInner.h"

namespace OpenAPI
{

/*
 * PlayerClientCommonOperationResponse
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientCommonOperationResponse : public Model
{
public:
    virtual ~PlayerClientCommonOperationResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class StatusEnum
	{
		_Signed,
		Pending,
		Rejected,
		Executed,
		Error,
  	};

	static FString EnumToString(const StatusEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, StatusEnum& EnumValue);
	StatusEnum Status;
	enum class ProcessingEnum
	{
		SignOnly,
		Execute,
  	};

	static FString EnumToString(const ProcessingEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ProcessingEnum& EnumValue);
	ProcessingEnum Processing;
	FString Id;
	FDateTime CreatedAt;
	TOptional<FDateTime> UpdatedAt;
	FString GameId;
	FString UserId;
	int64 ChainId = 0;
	FString Url;
	TArray<PlayerClientCommonOperationResponseTransactionsInner> Transactions;
};

}
