/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

class PLAYERCLIENT_API PlayerClientActivityApi
{
public:
	PlayerClientActivityApi();
	~PlayerClientActivityApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class GetAssetActivityRequest;
	class GetAssetActivityResponse;
	class GetContractActivityRequest;
	class GetContractActivityResponse;
	class GetUserActivityRequest;
	class GetUserActivityResponse;
	
    DECLARE_DELEGATE_OneParam(FGetAssetActivityDelegate, const GetAssetActivityResponse&);
    DECLARE_DELEGATE_OneParam(FGetContractActivityDelegate, const GetContractActivityResponse&);
    DECLARE_DELEGATE_OneParam(FGetUserActivityDelegate, const GetUserActivityResponse&);
    
    FHttpRequestPtr GetAssetActivity(const GetAssetActivityRequest& Request, const FGetAssetActivityDelegate& Delegate = FGetAssetActivityDelegate()) const;
    FHttpRequestPtr GetContractActivity(const GetContractActivityRequest& Request, const FGetContractActivityDelegate& Delegate = FGetContractActivityDelegate()) const;
    FHttpRequestPtr GetUserActivity(const GetUserActivityRequest& Request, const FGetUserActivityDelegate& Delegate = FGetUserActivityDelegate()) const;
    
private:
    void OnGetAssetActivityResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetAssetActivityDelegate Delegate) const;
    void OnGetContractActivityResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetContractActivityDelegate Delegate) const;
    void OnGetUserActivityResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetUserActivityDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
