/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "PlayerClientBaseModel.h"

namespace OpenAPI
{

/*
 * PlayerClientGetListedAssetsBodyInput
 *
 * 
 */
class PLAYERCLIENT_API PlayerClientGetListedAssetsBodyInput : public Model
{
public:
    virtual ~PlayerClientGetListedAssetsBodyInput() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<FString>> AssetAddresses;
	enum class SortByEnum
	{
		CreatedAt,
		UpdatedAt,
		Price,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	TOptional<SortByEnum> SortBy;
	enum class SortDirectionEnum
	{
		Asc,
		Desc,
  	};

	static FString EnumToString(const SortDirectionEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortDirectionEnum& EnumValue);
	/* If using `createdAt` for sorting, only `desc` is allowed. */
	TOptional<SortDirectionEnum> SortDirection;
	TOptional<int32> Limit;
	TOptional<int64> ChainId;
	TOptional<FString> Continuation;
};

}
