/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientAcceptAssetOfferRequestInput.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& Value)
{
	switch (Value)
	{
	case PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum::SignOnly:
		return TEXT("SignOnly");
	case PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum::Execute:
		return TEXT("Execute");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientAcceptAssetOfferRequestInput::EnumToString(const PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& Value)
{
	static TMap<FString, PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum> StringToEnum = { 
		{ TEXT("SignOnly"), PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum::SignOnly },
		{ TEXT("Execute"), PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum::Execute }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientAcceptAssetOfferRequestInput::EnumFromString(const FString& EnumAsString, PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientAcceptAssetOfferRequestInput::OperationProcessingEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& Value)
{
	switch (Value)
	{
	case PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Any:
		return TEXT("Any");
	case PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Google:
		return TEXT("Google");
	case PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Discord:
		return TEXT("Discord");
	case PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Apple:
		return TEXT("Apple");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientAcceptAssetOfferRequestInput::EnumToString(const PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& Value)
{
	static TMap<FString, PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum> StringToEnum = { 
		{ TEXT("Any"), PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Any },
		{ TEXT("Google"), PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Google },
		{ TEXT("Discord"), PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Discord },
		{ TEXT("Apple"), PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum::Apple }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientAcceptAssetOfferRequestInput::EnumFromString(const FString& EnumAsString, PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientAcceptAssetOfferRequestInput::AuthProviderEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientAcceptAssetOfferRequestInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("quantity")); WriteJsonValue(Writer, Quantity);
	if (Optimistic.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("optimistic")); WriteJsonValue(Writer, Optimistic.GetValue());
	}
	if (Sponsor.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sponsor")); WriteJsonValue(Writer, Sponsor.GetValue());
	}
	if (PolicyId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("policyId")); WriteJsonValue(Writer, PolicyId.GetValue());
	}
	if (ChainId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId.GetValue());
	}
	if (OperationProcessing.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("operationProcessing")); WriteJsonValue(Writer, OperationProcessing.GetValue());
	}
	if (AuthProvider.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("authProvider")); WriteJsonValue(Writer, AuthProvider.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientAcceptAssetOfferRequestInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("quantity"), Quantity);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("optimistic"), Optimistic);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sponsor"), Sponsor);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("policyId"), PolicyId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("operationProcessing"), OperationProcessing);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("authProvider"), AuthProvider);

	return ParseSuccess;
}

}
