/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetAssetsForContractBodyInput.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& Value)
{
	switch (Value)
	{
	case PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum::Asc:
		return TEXT("asc");
	case PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum::Desc:
		return TEXT("desc");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientGetAssetsForContractBodyInput::EnumToString(const PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& Value)
{
	static TMap<FString, PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum> StringToEnum = { 
		{ TEXT("asc"), PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum::Asc },
		{ TEXT("desc"), PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum::Desc }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientGetAssetsForContractBodyInput::EnumFromString(const FString& EnumAsString, PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientGetAssetsForContractBodyInput::SortDirectionEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientGetAssetsForContractBodyInput::SortByEnum& Value)
{
	switch (Value)
	{
	case PlayerClientGetAssetsForContractBodyInput::SortByEnum::FloorAskPrice:
		return TEXT("floorAskPrice");
	case PlayerClientGetAssetsForContractBodyInput::SortByEnum::TokenId:
		return TEXT("tokenId");
	case PlayerClientGetAssetsForContractBodyInput::SortByEnum::Rarity:
		return TEXT("rarity");
	case PlayerClientGetAssetsForContractBodyInput::SortByEnum::UpdatedAt:
		return TEXT("updatedAt");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientGetAssetsForContractBodyInput::SortByEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientGetAssetsForContractBodyInput::EnumToString(const PlayerClientGetAssetsForContractBodyInput::SortByEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientGetAssetsForContractBodyInput::SortByEnum& Value)
{
	static TMap<FString, PlayerClientGetAssetsForContractBodyInput::SortByEnum> StringToEnum = { 
		{ TEXT("floorAskPrice"), PlayerClientGetAssetsForContractBodyInput::SortByEnum::FloorAskPrice },
		{ TEXT("tokenId"), PlayerClientGetAssetsForContractBodyInput::SortByEnum::TokenId },
		{ TEXT("rarity"), PlayerClientGetAssetsForContractBodyInput::SortByEnum::Rarity },
		{ TEXT("updatedAt"), PlayerClientGetAssetsForContractBodyInput::SortByEnum::UpdatedAt }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientGetAssetsForContractBodyInput::EnumFromString(const FString& EnumAsString, PlayerClientGetAssetsForContractBodyInput::SortByEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientGetAssetsForContractBodyInput::SortByEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientGetAssetsForContractBodyInput::SortByEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientGetAssetsForContractBodyInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Continuation.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("continuation")); WriteJsonValue(Writer, Continuation.GetValue());
	}
	if (ChainId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId.GetValue());
	}
	if (MinRarityRank.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("minRarityRank")); WriteJsonValue(Writer, MinRarityRank.GetValue());
	}
	if (MaxRarityRank.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("maxRarityRank")); WriteJsonValue(Writer, MaxRarityRank.GetValue());
	}
	if (MinFloorAskPrice.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("minFloorAskPrice")); WriteJsonValue(Writer, MinFloorAskPrice.GetValue());
	}
	if (MaxFloorAskPrice.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("maxFloorAskPrice")); WriteJsonValue(Writer, MaxFloorAskPrice.GetValue());
	}
	if (IncludeAttributes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("includeAttributes")); WriteJsonValue(Writer, IncludeAttributes.GetValue());
	}
	if (Attributes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("attributes")); WriteJsonValue(Writer, Attributes.GetValue());
	}
	if (SortDirection.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sortDirection")); WriteJsonValue(Writer, SortDirection.GetValue());
	}
	if (SortBy.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sortBy")); WriteJsonValue(Writer, SortBy.GetValue());
	}
	if (Limit.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("limit")); WriteJsonValue(Writer, Limit.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientGetAssetsForContractBodyInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("continuation"), Continuation);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("minRarityRank"), MinRarityRank);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("maxRarityRank"), MaxRarityRank);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("minFloorAskPrice"), MinFloorAskPrice);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("maxFloorAskPrice"), MaxFloorAskPrice);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("includeAttributes"), IncludeAttributes);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("attributes"), Attributes);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sortDirection"), SortDirection);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sortBy"), SortBy);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("limit"), Limit);

	return ParseSuccess;
}

}
