/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientTransferNativeTokenRequestInput.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& Value)
{
	switch (Value)
	{
	case PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum::SignOnly:
		return TEXT("SignOnly");
	case PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum::Execute:
		return TEXT("Execute");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientTransferNativeTokenRequestInput::EnumToString(const PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& Value)
{
	static TMap<FString, PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum> StringToEnum = { 
		{ TEXT("SignOnly"), PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum::SignOnly },
		{ TEXT("Execute"), PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum::Execute }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientTransferNativeTokenRequestInput::EnumFromString(const FString& EnumAsString, PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientTransferNativeTokenRequestInput::OperationProcessingEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientTransferNativeTokenRequestInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (ReceiverEntityId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("receiverEntityId")); WriteJsonValue(Writer, ReceiverEntityId.GetValue());
	}
	if (ReceiverWalletAddress.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("receiverWalletAddress")); WriteJsonValue(Writer, ReceiverWalletAddress.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("amountToTransfer")); WriteJsonValue(Writer, AmountToTransfer);
	if (Optimistic.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("optimistic")); WriteJsonValue(Writer, Optimistic.GetValue());
	}
	if (Sponsor.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sponsor")); WriteJsonValue(Writer, Sponsor.GetValue());
	}
	if (PolicyId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("policyId")); WriteJsonValue(Writer, PolicyId.GetValue());
	}
	if (ChainId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId.GetValue());
	}
	if (OperationProcessing.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("operationProcessing")); WriteJsonValue(Writer, OperationProcessing.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientTransferNativeTokenRequestInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("receiverEntityId"), ReceiverEntityId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("receiverWalletAddress"), ReceiverWalletAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amountToTransfer"), AmountToTransfer);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("optimistic"), Optimistic);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sponsor"), Sponsor);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("policyId"), PolicyId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("operationProcessing"), OperationProcessing);

	return ParseSuccess;
}

}
