/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetAssetsForContractResponseDataInner.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& Value)
{
	switch (Value)
	{
	case PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Common:
		return TEXT("Common");
	case PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Uncommon:
		return TEXT("Uncommon");
	case PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Rare:
		return TEXT("Rare");
	case PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::VeryRare:
		return TEXT("VeryRare");
	case PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::ExtremelyRare:
		return TEXT("ExtremelyRare");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientGetAssetsForContractResponseDataInner::RarityEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientGetAssetsForContractResponseDataInner::EnumToString(const PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& Value)
{
	static TMap<FString, PlayerClientGetAssetsForContractResponseDataInner::RarityEnum> StringToEnum = { 
		{ TEXT("Common"), PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Common },
		{ TEXT("Uncommon"), PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Uncommon },
		{ TEXT("Rare"), PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::Rare },
		{ TEXT("VeryRare"), PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::VeryRare },
		{ TEXT("ExtremelyRare"), PlayerClientGetAssetsForContractResponseDataInner::RarityEnum::ExtremelyRare }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientGetAssetsForContractResponseDataInner::EnumFromString(const FString& EnumAsString, PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientGetAssetsForContractResponseDataInner::RarityEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientGetAssetsForContractResponseDataInner::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("imageUrl")); WriteJsonValue(Writer, ImageUrl);
	Writer->WriteIdentifierPrefix(TEXT("assetType")); WriteJsonValue(Writer, AssetType);
	Writer->WriteIdentifierPrefix(TEXT("assetAddress")); WriteJsonValue(Writer, AssetAddress);
	Writer->WriteIdentifierPrefix(TEXT("assetId")); WriteJsonValue(Writer, AssetId);
	Writer->WriteIdentifierPrefix(TEXT("supply")); WriteJsonValue(Writer, Supply);
	if (Rarity.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rarity")); WriteJsonValue(Writer, Rarity.GetValue());
	}
	if (RarityScore.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rarityScore")); WriteJsonValue(Writer, RarityScore.GetValue());
	}
	if (Attributes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("attributes")); WriteJsonValue(Writer, Attributes.GetValue());
	}
	if (ChainId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientGetAssetsForContractResponseDataInner::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("imageUrl"), ImageUrl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("assetType"), AssetType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("assetAddress"), AssetAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("assetId"), AssetId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("supply"), Supply);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("rarity"), Rarity);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("rarityScore"), RarityScore);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("attributes"), Attributes);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);

	return ParseSuccess;
}

}
