/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetUserResponse.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetUserResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("externalEntityId")); WriteJsonValue(Writer, ExternalEntityId);
	Writer->WriteIdentifierPrefix(TEXT("userId")); WriteJsonValue(Writer, UserId);
	Writer->WriteIdentifierPrefix(TEXT("gameId")); WriteJsonValue(Writer, GameId);
	Writer->WriteIdentifierPrefix(TEXT("wallets")); WriteJsonValue(Writer, Wallets);
	Writer->WriteIdentifierPrefix(TEXT("entities")); WriteJsonValue(Writer, Entities);
	Writer->WriteObjectEnd();
}

bool PlayerClientGetUserResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("externalEntityId"), ExternalEntityId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("userId"), UserId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("gameId"), GameId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("wallets"), Wallets);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("entities"), Entities);

	return ParseSuccess;
}

}
