/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientHealthApiOperations.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include <string>
#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace OpenAPI
{

FString PlayerClientHealthApi::CheckRequest::ComputePath() const
{
	FString Path(TEXT("/v1/health/services"));
	return Path;
}

void PlayerClientHealthApi::CheckRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void PlayerClientHealthApi::CheckResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);

        if ((int)InHttpResponseCode == 200)
        {
            SetResponseString(TEXT("The Health Check is successful"));
            return;
        }
        if ((int)InHttpResponseCode == 503)
        {
            SetResponseString(TEXT("The Health Check is not successful"));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "4XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "5XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
}

std::string PlayerClientHealthApi::CheckResponse::GetHttpStatusCategory(EHttpResponseCodes::Type InHttpResponseCode) {
    int statusCode = (int)InHttpResponseCode;

    // Ensure the input is a valid 3-digit HTTP status code
    if (statusCode < 100 || statusCode > 599) {
    throw std::invalid_argument("Invalid HTTP status code. Must be between 100 and 599.");
    }

    // Extract the first digit and append "XX"
    int firstDigit = statusCode / 100;
    return std::to_string(firstDigit) + "XX";
}

bool PlayerClientHealthApi::CheckResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
