/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientExchangeApi.h"

#include "PlayerClientExchangeApiOperations.h"
#include "PlayerClientModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace OpenAPI
{

PlayerClientExchangeApi::PlayerClientExchangeApi()
: Url(TEXT("http://localhost"))
{
}

PlayerClientExchangeApi::~PlayerClientExchangeApi() {}

void PlayerClientExchangeApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void PlayerClientExchangeApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void PlayerClientExchangeApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool PlayerClientExchangeApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogPlayerClient, Error, TEXT("PlayerClientExchangeApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void PlayerClientExchangeApi::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if (RetryManager != &InRetryManager)
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& PlayerClientExchangeApi::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("PlayerClientExchangeApi: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef PlayerClientExchangeApi::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void PlayerClientExchangeApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty())
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogPlayerClient, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr PlayerClientExchangeApi::ConvertInput(const ConvertInputRequest& Request, const FConvertInputDelegate& Delegate /*= FConvertInputDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnConvertInputResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnConvertInputResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FConvertInputDelegate Delegate) const
{
	ConvertInputResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr PlayerClientExchangeApi::ConvertToOutput(const ConvertToOutputRequest& Request, const FConvertToOutputDelegate& Delegate /*= FConvertToOutputDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnConvertToOutputResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnConvertToOutputResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FConvertToOutputDelegate Delegate) const
{
	ConvertToOutputResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr PlayerClientExchangeApi::GetQuoteForInput(const GetQuoteForInputRequest& Request, const FGetQuoteForInputDelegate& Delegate /*= FGetQuoteForInputDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnGetQuoteForInputResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnGetQuoteForInputResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetQuoteForInputDelegate Delegate) const
{
	GetQuoteForInputResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr PlayerClientExchangeApi::GetQuoteForOutput(const GetQuoteForOutputRequest& Request, const FGetQuoteForOutputDelegate& Delegate /*= FGetQuoteForOutputDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnGetQuoteForOutputResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnGetQuoteForOutputResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetQuoteForOutputDelegate Delegate) const
{
	GetQuoteForOutputResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr PlayerClientExchangeApi::UnwrapNative(const UnwrapNativeRequest& Request, const FUnwrapNativeDelegate& Delegate /*= FUnwrapNativeDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnUnwrapNativeResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnUnwrapNativeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnwrapNativeDelegate Delegate) const
{
	UnwrapNativeResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr PlayerClientExchangeApi::WrapNative(const WrapNativeRequest& Request, const FWrapNativeDelegate& Delegate /*= FWrapNativeDelegate()*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindRaw(this, &PlayerClientExchangeApi::OnWrapNativeResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void PlayerClientExchangeApi::OnWrapNativeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FWrapNativeDelegate Delegate) const
{
	WrapNativeResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
