/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("symbol")); WriteJsonValue(Writer, Symbol);
	Writer->WriteIdentifierPrefix(TEXT("decimals")); WriteJsonValue(Writer, Decimals);
	if (LogoUri.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("logoUri")); WriteJsonValue(Writer, LogoUri.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId);
	Writer->WriteIdentifierPrefix(TEXT("balance")); WriteJsonValue(Writer, Balance);
	Writer->WriteObjectEnd();
}

bool PlayerClientGetUserNativeCurrencyResponseNativeTokenBalance::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("symbol"), Symbol);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("decimals"), Decimals);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("logoUri"), LogoUri);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("balance"), Balance);

	return ParseSuccess;
}

}
