/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetTransactionResponseUser.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetTransactionResponseUser::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("entities")); WriteJsonValue(Writer, Entities);
	Writer->WriteIdentifierPrefix(TEXT("wallet")); WriteJsonValue(Writer, Wallet);
	Writer->WriteObjectEnd();
}

bool PlayerClientGetTransactionResponseUser::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("entities"), Entities);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("wallet"), Wallet);

	return ParseSuccess;
}

}
