/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientConnectorApiOperations.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include <string>
#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace OpenAPI
{

FString PlayerClientConnectorApi::CreateConnectionRequestRequest::ComputePath() const
{
	FString Path(TEXT("/v1/connection/request"));
	return Path;
}

void PlayerClientConnectorApi::CreateConnectionRequestRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Body parameters
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);

		WriteJsonValue(Writer, PlayerClientCreateConnectionRequestInput);
		Writer->Close();

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		UE_LOG(LogPlayerClient, Error, TEXT("Body parameter (PlayerClientCreateConnectionRequestInput) was ignored, not supported in multipart form"));
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		UE_LOG(LogPlayerClient, Error, TEXT("Body parameter (PlayerClientCreateConnectionRequestInput) was ignored, not supported in urlencoded requests"));
	}
	else
	{
		UE_LOG(LogPlayerClient, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void PlayerClientConnectorApi::CreateConnectionRequestResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);

        if ((int)InHttpResponseCode == 200)
        {
            SetResponseString(TEXT(""));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "4XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "5XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
}

std::string PlayerClientConnectorApi::CreateConnectionRequestResponse::GetHttpStatusCategory(EHttpResponseCodes::Type InHttpResponseCode) {
    int statusCode = (int)InHttpResponseCode;

    // Ensure the input is a valid 3-digit HTTP status code
    if (statusCode < 100 || statusCode > 599) {
    throw std::invalid_argument("Invalid HTTP status code. Must be between 100 and 599.");
    }

    // Extract the first digit and append "XX"
    int firstDigit = statusCode / 100;
    return std::to_string(firstDigit) + "XX";
}

bool PlayerClientConnectorApi::CreateConnectionRequestResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString PlayerClientConnectorApi::GetConnectionRequestRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("requestId"), FStringFormatArg(ToUrlString(RequestId)) } };

	FString Path = FString::Format(TEXT("/v1/connection/request/{requestId}"), PathParams);

	return Path;
}

void PlayerClientConnectorApi::GetConnectionRequestRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void PlayerClientConnectorApi::GetConnectionRequestResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);

        if ((int)InHttpResponseCode == 200)
        {
            SetResponseString(TEXT(""));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "4XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
        if (GetHttpStatusCategory(InHttpResponseCode) == "5XX")
        {
            SetResponseString(TEXT(""));
            return;
        }
}

std::string PlayerClientConnectorApi::GetConnectionRequestResponse::GetHttpStatusCategory(EHttpResponseCodes::Type InHttpResponseCode) {
    int statusCode = (int)InHttpResponseCode;

    // Ensure the input is a valid 3-digit HTTP status code
    if (statusCode < 100 || statusCode > 599) {
    throw std::invalid_argument("Invalid HTTP status code. Must be between 100 and 599.");
    }

    // Extract the first digit and append "XX"
    int firstDigit = statusCode / 100;
    return std::to_string(firstDigit) + "XX";
}

bool PlayerClientConnectorApi::GetConnectionRequestResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
