/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetQuoteResponse.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetQuoteResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("tokenIn")); WriteJsonValue(Writer, TokenIn);
	Writer->WriteIdentifierPrefix(TEXT("tokenOut")); WriteJsonValue(Writer, TokenOut);
	Writer->WriteIdentifierPrefix(TEXT("amountIn")); WriteJsonValue(Writer, AmountIn);
	Writer->WriteIdentifierPrefix(TEXT("amountOut")); WriteJsonValue(Writer, AmountOut);
	Writer->WriteObjectEnd();
}

bool PlayerClientGetQuoteResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("tokenIn"), TokenIn);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("tokenOut"), TokenOut);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amountIn"), AmountIn);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("amountOut"), AmountOut);

	return ParseSuccess;
}

}
