/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientCommonOperationResponse.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientCommonOperationResponse::StatusEnum& Value)
{
	switch (Value)
	{
	case PlayerClientCommonOperationResponse::StatusEnum::_Signed:
		return TEXT("Signed");
	case PlayerClientCommonOperationResponse::StatusEnum::Pending:
		return TEXT("Pending");
	case PlayerClientCommonOperationResponse::StatusEnum::Rejected:
		return TEXT("Rejected");
	case PlayerClientCommonOperationResponse::StatusEnum::Executed:
		return TEXT("Executed");
	case PlayerClientCommonOperationResponse::StatusEnum::Error:
		return TEXT("Error");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientCommonOperationResponse::StatusEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientCommonOperationResponse::EnumToString(const PlayerClientCommonOperationResponse::StatusEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientCommonOperationResponse::StatusEnum& Value)
{
	static TMap<FString, PlayerClientCommonOperationResponse::StatusEnum> StringToEnum = { 
		{ TEXT("Signed"), PlayerClientCommonOperationResponse::StatusEnum::_Signed },
		{ TEXT("Pending"), PlayerClientCommonOperationResponse::StatusEnum::Pending },
		{ TEXT("Rejected"), PlayerClientCommonOperationResponse::StatusEnum::Rejected },
		{ TEXT("Executed"), PlayerClientCommonOperationResponse::StatusEnum::Executed },
		{ TEXT("Error"), PlayerClientCommonOperationResponse::StatusEnum::Error }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientCommonOperationResponse::EnumFromString(const FString& EnumAsString, PlayerClientCommonOperationResponse::StatusEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientCommonOperationResponse::StatusEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientCommonOperationResponse::StatusEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientCommonOperationResponse::ProcessingEnum& Value)
{
	switch (Value)
	{
	case PlayerClientCommonOperationResponse::ProcessingEnum::SignOnly:
		return TEXT("SignOnly");
	case PlayerClientCommonOperationResponse::ProcessingEnum::Execute:
		return TEXT("Execute");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientCommonOperationResponse::ProcessingEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientCommonOperationResponse::EnumToString(const PlayerClientCommonOperationResponse::ProcessingEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientCommonOperationResponse::ProcessingEnum& Value)
{
	static TMap<FString, PlayerClientCommonOperationResponse::ProcessingEnum> StringToEnum = { 
		{ TEXT("SignOnly"), PlayerClientCommonOperationResponse::ProcessingEnum::SignOnly },
		{ TEXT("Execute"), PlayerClientCommonOperationResponse::ProcessingEnum::Execute }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientCommonOperationResponse::EnumFromString(const FString& EnumAsString, PlayerClientCommonOperationResponse::ProcessingEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientCommonOperationResponse::ProcessingEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientCommonOperationResponse::ProcessingEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientCommonOperationResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	Writer->WriteIdentifierPrefix(TEXT("processing")); WriteJsonValue(Writer, Processing);
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	Writer->WriteIdentifierPrefix(TEXT("createdAt")); WriteJsonValue(Writer, CreatedAt);
	if (UpdatedAt.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("updatedAt")); WriteJsonValue(Writer, UpdatedAt.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("gameId")); WriteJsonValue(Writer, GameId);
	Writer->WriteIdentifierPrefix(TEXT("userId")); WriteJsonValue(Writer, UserId);
	Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId);
	Writer->WriteIdentifierPrefix(TEXT("url")); WriteJsonValue(Writer, Url);
	Writer->WriteIdentifierPrefix(TEXT("transactions")); WriteJsonValue(Writer, Transactions);
	Writer->WriteObjectEnd();
}

bool PlayerClientCommonOperationResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("status"), Status);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("processing"), Processing);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("createdAt"), CreatedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("updatedAt"), UpdatedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("gameId"), GameId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("userId"), UserId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("url"), Url);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transactions"), Transactions);

	return ParseSuccess;
}

}
