/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientCommonOperationResponseTransactionsInner.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& Value)
{
	switch (Value)
	{
	case PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortTransaction:
		return TEXT("OpenfortTransaction");
	case PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortReservoirOrder:
		return TEXT("OpenfortReservoirOrder");
	case PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortRevokeSession:
		return TEXT("OpenfortRevokeSession");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientCommonOperationResponseTransactionsInner::TypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientCommonOperationResponseTransactionsInner::EnumToString(const PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& Value)
{
	static TMap<FString, PlayerClientCommonOperationResponseTransactionsInner::TypeEnum> StringToEnum = { 
		{ TEXT("OpenfortTransaction"), PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortTransaction },
		{ TEXT("OpenfortReservoirOrder"), PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortReservoirOrder },
		{ TEXT("OpenfortRevokeSession"), PlayerClientCommonOperationResponseTransactionsInner::TypeEnum::OpenfortRevokeSession }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientCommonOperationResponseTransactionsInner::EnumFromString(const FString& EnumAsString, PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientCommonOperationResponseTransactionsInner::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& Value)
{
	switch (Value)
	{
	case PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Pending:
		return TEXT("Pending");
	case PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::_Signed:
		return TEXT("Signed");
	case PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Rejected:
		return TEXT("Rejected");
	case PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Executed:
		return TEXT("Executed");
	case PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Error:
		return TEXT("Error");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientCommonOperationResponseTransactionsInner::StatusEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientCommonOperationResponseTransactionsInner::EnumToString(const PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& Value)
{
	static TMap<FString, PlayerClientCommonOperationResponseTransactionsInner::StatusEnum> StringToEnum = { 
		{ TEXT("Pending"), PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Pending },
		{ TEXT("Signed"), PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::_Signed },
		{ TEXT("Rejected"), PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Rejected },
		{ TEXT("Executed"), PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Executed },
		{ TEXT("Error"), PlayerClientCommonOperationResponseTransactionsInner::StatusEnum::Error }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientCommonOperationResponseTransactionsInner::EnumFromString(const FString& EnumAsString, PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientCommonOperationResponseTransactionsInner::StatusEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientCommonOperationResponseTransactionsInner::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	if (ExternalId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("externalId")); WriteJsonValue(Writer, ExternalId.GetValue());
	}
	if (Signature.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("signature")); WriteJsonValue(Writer, Signature.GetValue());
	}
	if (TransactionHash.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("transactionHash")); WriteJsonValue(Writer, TransactionHash.GetValue());
	}
	if (OperationId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("operationId")); WriteJsonValue(Writer, OperationId.GetValue());
	}
	if (Data.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("data")); WriteJsonValue(Writer, Data.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("hash")); WriteJsonValue(Writer, Hash);
	Writer->WriteObjectEnd();
}

bool PlayerClientCommonOperationResponseTransactionsInner::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("status"), Status);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("externalId"), ExternalId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("signature"), Signature);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transactionHash"), TransactionHash);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("operationId"), OperationId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("data"), Data);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("hash"), Hash);

	return ParseSuccess;
}

}
