/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientCommonContractActivityRequestInput.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const PlayerClientCommonContractActivityRequestInput::TypesEnum& Value)
{
	switch (Value)
	{
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::Ask:
		return TEXT("ask");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::AskCancel:
		return TEXT("ask_cancel");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::Bid:
		return TEXT("bid");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::BidCancel:
		return TEXT("bid_cancel");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::Sale:
		return TEXT("sale");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::Mint:
		return TEXT("mint");
	case PlayerClientCommonContractActivityRequestInput::TypesEnum::Transfer:
		return TEXT("transfer");
	}

	UE_LOG(LogPlayerClient, Error, TEXT("Invalid PlayerClientCommonContractActivityRequestInput::TypesEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString PlayerClientCommonContractActivityRequestInput::EnumToString(const PlayerClientCommonContractActivityRequestInput::TypesEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, PlayerClientCommonContractActivityRequestInput::TypesEnum& Value)
{
	static TMap<FString, PlayerClientCommonContractActivityRequestInput::TypesEnum> StringToEnum = { 
		{ TEXT("ask"), PlayerClientCommonContractActivityRequestInput::TypesEnum::Ask },
		{ TEXT("ask_cancel"), PlayerClientCommonContractActivityRequestInput::TypesEnum::AskCancel },
		{ TEXT("bid"), PlayerClientCommonContractActivityRequestInput::TypesEnum::Bid },
		{ TEXT("bid_cancel"), PlayerClientCommonContractActivityRequestInput::TypesEnum::BidCancel },
		{ TEXT("sale"), PlayerClientCommonContractActivityRequestInput::TypesEnum::Sale },
		{ TEXT("mint"), PlayerClientCommonContractActivityRequestInput::TypesEnum::Mint },
		{ TEXT("transfer"), PlayerClientCommonContractActivityRequestInput::TypesEnum::Transfer }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool PlayerClientCommonContractActivityRequestInput::EnumFromString(const FString& EnumAsString, PlayerClientCommonContractActivityRequestInput::TypesEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const PlayerClientCommonContractActivityRequestInput::TypesEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, PlayerClientCommonContractActivityRequestInput::TypesEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void PlayerClientCommonContractActivityRequestInput::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Limit.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("limit")); WriteJsonValue(Writer, Limit.GetValue());
	}
	if (Types.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("types")); WriteJsonValue(Writer, Types.GetValue());
	}
	if (ChainId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("chainId")); WriteJsonValue(Writer, ChainId.GetValue());
	}
	if (Continuation.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("continuation")); WriteJsonValue(Writer, Continuation.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientCommonContractActivityRequestInput::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("limit"), Limit);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("types"), Types);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chainId"), ChainId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("continuation"), Continuation);

	return ParseSuccess;
}

}
