/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetActiveSessionResponseV2.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetActiveSessionResponseV2::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Session.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("session")); WriteJsonValue(Writer, Session.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool PlayerClientGetActiveSessionResponseV2::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("session"), Session);

	return ParseSuccess;
}

}
