/**
 * Player API
 * The Player API is a service to integrate your game with Beam
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "PlayerClientGetAssetListingsResponseDataInnerPriceAmount.h"

#include "PlayerClientModule.h"
#include "PlayerClientHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void PlayerClientGetAssetListingsResponseDataInnerPriceAmount::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("raw")); WriteJsonValue(Writer, Raw);
	Writer->WriteIdentifierPrefix(TEXT("decimal")); WriteJsonValue(Writer, Decimal);
	Writer->WriteIdentifierPrefix(TEXT("usd")); WriteJsonValue(Writer, Usd);
	Writer->WriteIdentifierPrefix(TEXT("native")); WriteJsonValue(Writer, Native);
	Writer->WriteObjectEnd();
}

bool PlayerClientGetAssetListingsResponseDataInnerPriceAmount::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("raw"), Raw);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("decimal"), Decimal);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("usd"), Usd);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("native"), Native);

	return ParseSuccess;
}

}
